version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
